### ISSUE TITLE
Form OpenColorIO configs working group

### ISSUE THREAD

**Issue by michdolan** [AcademySoftwareFoundation/OpenColorIO-Config-ACES#1]
Form working group to discuss creation and management of OCIO-curated configs, and in particular direction for a new ACES config.

**Comment by michdolan** [comment]
@KelSolaar @mlfp @scoopxyz @doug-walker we should discuss how to proceed. Do any of you have interest in leading a working group for this effort? I think it will be good to get a meeting on the books to discuss first steps.

**Comment by KelSolaar** [comment]
Hi,

I was not blessed with a lot of spare cycles lately (ACES VWG, Colour, GSoC, etc...) and I don't know if I will have time to lead the effort with the attention required.

However, I started to look at some stuff, mostly related to discovering the transforms in ACES-dev: https://github.com/colour-science/discover-aces-dev, my hope is to build-up on something like that to auto-magically generate most of the required _ColorSpaces_.

Certainly keen to be part of any meeting :)

**Comment by KelSolaar** [comment]
Steering the pot a bit more while there is momentum, found some spare cycles to continue poking at the discovery thing, uncovering unpleasant surprises doing so: https://github.com/ampas/aces-dev/issues/118

Here is an abridged log of the transformations the discovery process is able to find:

https://gist.github.com/KelSolaar/0c534f01507b8735b941624f87032efb

**Comment by KelSolaar** [comment]
With the OCIO2 meeting on the 18th/19th would it make sense to schedule something not too far?

**Comment by michdolan** [comment]
Thanks @KelSolaar ! Yes we should schedule something soon. One topic we need to discuss in particular is the intentions for what the next gen ACES config will be. In discussions so far there have been two proposed ideas:

1. ACES "reference" config, which implements only ACES transforms (in theory matching the transforms outlined by your discovery code.

2.  Super config, which is ACES-based, but fulfills the role the current ACES configs hold by providing a wide range of transforms which are useful for production. This config plays a particularly important role for studios that want to leverage OCIO but don't necessarily have a color expert in-house to develop something custom from a reference config.

My opinion is that we should create both of these, and that they can probably share the same generation code base. To look at it in programming terms, The ACES reference config is the base class, and the super config is the ready-to-use implementation. 

What about scheduling a Zoom meeting this coming Friday at 4pm EST (1pm PST)? That's the typical ASWF time zone convergence hour. The goals of the meeting will be to establish some initial direction so that those that have time to contribute can start investigations and/or prototypes, or at least to figure out next steps.

**Comment by KelSolaar** [comment]
Plan sounds good and along the lines of what I had in mind!

Time is fine albeit being on weekend:

![image](https://user-images.githubusercontent.com/99779/84109272-64123880-aa76-11ea-9479-b8a13dca1439.png)

https://www.timeanddate.com/worldclock/converter.html?iso=20200612T200000&p1=tz_et&p2=264

**Comment by michdolan** [comment]
Cool. Thanks for pointing out my timezone miss... let's not do Saturdays. What about next week, Tuesday (your Wednesday)? Ideally it's far enough out to give notice to all interested parties. Other days can work too if something is better on your calendar.

**Comment by KelSolaar** [comment]
Wednesday works!

**Comment by michdolan** [comment]
ocio-dev event:

https://lists.aswf.io/g/ocio-dev/viewevent?eventid=834599&calstart=2020-06-16

**Comment by KelSolaar** [comment]
Tempted to say that this one is very much covered! :)
