### ISSUE TITLE
2023-08 release planning

### ISSUE THREAD

**Issue by doug-walker** [AcademySoftwareFoundation/OpenColorIO-Config-ACES#102]
We are planning our next release of the OCIO configs for ACES.  The plan is to include these as built-in configs in the upcoming OCIO 2.3 release.  The VFX Reference Platform leadership has asked us to have the library released by the end of August in order to be included in the VFX Reference Platform for CY 2024, so we need to have the configs available by early August so that we have time to integrate them into the library.

I've created a [spreadsheet](https://docs.google.com/spreadsheets/d/1miqwGK7t_vTj7-e1_P99ANN9tgWq3GwofV_JTZMgiso/edit?usp=sharing) to help with the release planning.

Per the discussion at today's Configs WG, I've bumped the config part of the version string to 2.0.0 for the upcoming release.  The ACES version will remain at 1.3.  

I'm proposing bumping the OCIO version to 2.3 to take advantage of the latest built-ins.  But what older OCIO releases do we want to support?  Please add the proposed name, and what features you want included, to the spreadsheet.  (Note that any configs for older versions will not be built into the 2.3 library, so these could be added to the Python generator later, if necessary.)

**Comment by KelSolaar** [comment]
The configs were released, closing this one!
