### ISSUE TITLE
Fix matte_paint and texture_paint role assignments

### ISSUE THREAD

**Issue by carolalynn22** [AcademySoftwareFoundation/OpenColorIO-Config-ACES#107]
In v1 of these config releases, the working group decided to maintain parity with previous OCIOv1 ACES config releases with respect to the matte_paint and texture_paint roles. We made this decision to minimize disruption to applications wishing to make use of the new configs in the short term. 

With the upcoming release of v2 of the configs, the group has decided the time is ripe to make the needed switch from:

```
  matte_paint: sRGB - Texture
  texture_paint: ACEScct
``` 
to the new:

```
  matte_paint: ACEScct
  texture_paint: sRGB - Texture
``` 

This issue is just to serve as documentation for the forthcoming PRs.

**Comment by doug-walker** [comment]
This has been implemented. The roles are switched in config version 2 and higher, per the working group discussion.
