### ISSUE TITLE
Add support for Apple Log

### ISSUE THREAD

**Issue by rkmolholm** [AcademySoftwareFoundation/OpenColorIO-Config-ACES#120]
**Request:**
Addition of Apple Log to the OpenColorIO ACES config. I suspect this also means the addition of a new "Input/Apple" family.

**Reference implementation:**
A CTL-based Apple Log IDT was recently added to aces-dev at:
https://github.com/ampas/aces-dev/tree/dev/transforms/ctl/idt/vendorSupplied/apple

**Documentation:**
The official white paper, and example 1D LUT (.cube) are located here:
https://developer.apple.com/download/all/?q=Apple%20log%20profile

**Comment by carolalynn22** [comment]
Related issue for adding built-in transform support to the main OCIO library: https://github.com/AcademySoftwareFoundation/OpenColorIO/issues/1916

**Comment by JGoldstone** [comment]
I'll have a run at these.

**Comment by KelSolaar** [comment]
Closing this one as @JGoldstone PR was merged: #125
