### ISSUE TITLE
Missing encoding attribute for some color spaces

### ISSUE THREAD

**Issue by doug-walker** [AcademySoftwareFoundation/OpenColorIO-Config-ACES#123]
As reported on Slack, srgb_texture is missing the encoding attribute (should be "sdr-video"). 

Update -- in addition, the 'CIE-XYZ-D65' color space should have the encoding 'display-linear', and 'Raw' should have the encoding 'data'.   All other color spaces and named transforms in the Studio config have the encoding set.

**Comment by KelSolaar** [comment]
![image](https://github.com/AcademySoftwareFoundation/OpenColorIO-Config-ACES/assets/99779/1397c9b3-97a8-40a0-93b9-db8e41e1bb6d)

**Comment by KelSolaar** [comment]
Should be addressed in #129!

**Comment by doug-walker** [comment]
Validated that this is fixed in studio-config-v2.2.0_aces-v1.3_ocio-v2.4.ocio.  Closing as fixed in #129.
