### ISSUE TITLE
Make the display color spaces active

### ISSUE THREAD

**Issue by doug-walker** [AcademySoftwareFoundation/OpenColorIO-Config-ACES#124]
Currently the display color spaces are inactive. But this makes it difficult for people to invert view transforms. For example, bringing in an sRGB image as a back plate or image plane that will be shown under a view transform, but that view transform was effectively already applied to the source.

We had a long discussion about this before originally making them inactive, as there are a number of issues, but we should revisit to see if all of them are still valid.

If we do this, we should make Un-tone-mapped the first view transform in the list to work around a bug that is still present in older releases (prior to OCIO 2.3.1).

**Comment by KelSolaar** [comment]
This should be fixed in #129.

**Comment by doug-walker** [comment]
Closing, was display spaces were made active in #129.

However, Un-tone-mapped is not the first view transform, so we should probably do a patch release for OCIO library 2.2.x and 2.1.x to port back the fix for that related issue.
