### ISSUE TITLE
help a demo .

### ISSUE THREAD

**Issue by luoww1992** [AcademySoftwareFoundation/OpenColorIO-Config-ACES#42]
i am a newbire in learning ACES,
i have changed the colorspace to 709  by lut file.
now i am trying to change colorspace  from RED log3G10 to sRGB by ACES.
but i dont't konw to do it .
can you support a demo about log3G10 to sRGB?
thank you !

**Comment by KelSolaar** [comment]
Hi @luoww1992,

Sorry for the late reply, I would recommend reaching out on [Slack](http://slack.opencolorio.org/) or the [mailing list](https://lists.aswf.io/g/ocio-user) for support questions.

Cheers,

Thomas
