### ISSUE TITLE
Add aliases to the configs

### ISSUE THREAD

**Issue by doug-walker** [AcademySoftwareFoundation/OpenColorIO-Config-ACES#44]
In OCIO v2, a colorspace may have an aliases attribute that provides alternate names for the color space.  This allows configs to be more compact than the earlier ACES configs (which duplicated each color space to define the alternate name).

The spreadsheet of color spaces has a column for the alias strings (although they may need to be refined).  In the Python, these strings may be provided as a list in the ColorSpace constructor or later individually using the addAlias method.

It seems there is code to add these at line 194 in: 
[opencolorio_config_aces/config/generation/factories.py](https://github.com/AcademySoftwareFoundation/OpenColorIO-Config-ACES/blob/d588eac7fc453ea55454fc7f04ad71bac85b339e/opencolorio_config_aces/config/generation/factories.py)

But the aliases don't seem to be showing up in the config.  Is it an issue in the code or the spreadsheet or something else?

**Comment by KelSolaar** [comment]
Hey @doug-walker,

The alias column is not added to the pivot tables of the Reference and CG config, so we need to do that and then ensure that the value is passed to the respective generators. Should hopefully be trivial!

Cheers,

Thomas
