### ISSUE TITLE
instant crash with exr textures OpenColorIO-Config-ACES 0.2.0 blender 3.2

### ISSUE THREAD

**Issue by 356Fab** [AcademySoftwareFoundation/OpenColorIO-Config-ACES#46]
I get instant crash when i try to use exr half float textures blender 3.1 or 3.2   
with the beta profile OpenColorIO-Config-ACES 0.2.0

**Comment by KelSolaar** [comment]
Hello @356Fab,

Is this still an issue? The configs are working fine in Nuke and various other DCC softwares, it could be an issue with OCIO but the config itself should not be the cause of the crash.

Cheers,

Thomas

**Comment by KelSolaar** [comment]
I will close this one as we haven't heard from you @356Fab, feel free to bump the issue and we will reopen!

Cheers,

Thomas
