### ISSUE TITLE
Add pure gamma 2.2 display to ACES configs

### ISSUE THREAD

**Issue by sharktacos** [AcademySoftwareFoundation/OpenColorIO-Config-ACES#56]
Proposing adding a pure gamma 2.2 display to the ACES configs (CG and Studio) alongside the existing sRGB (Piece-Wise) display. FWIW, this would parallel the "Gamma 2.2/Rec 709" display in the default Maya config.

As many folks have noted, it seems like a safer bet generally for CG/VFX artists to use a pure gamma 2.2 display to avoid crushed shadows.

**Comment by KelSolaar** [comment]
Hi @sharktacos,

We will be discussing about that post-Siggraph!

Cheers,

Thomas

**Comment by doug-walker** [comment]
We discussed this at the most recent configs working group meeting and decided to limit ourselves to the displays defined by the ACES 1.3 release, for this upcoming initial release of the configs.  However, it is a valid request and so we should probably leave the issue open.  Maybe we will get more feedback on this topic and will revisit for a future release.

In the meantime, it would be simple to add such a display color space to the ACES configs.  OCIO already has a Built-in Transform for it.  The style string to use is "DISPLAY - CIE-XYZ-D65_to_G2.2-REC.709".

**Comment by carolalynn** [comment]
Closing this as it's old and hasn't come up again (probably because it's easy to add with the built-in). Folks can feel free to re-open as needed.

**Comment by doug-walker** [comment]
Note that this display is part of ACES 2 and will be in the OCIO configs for ACES 2.

**Comment by sharktacos** [comment]
@doug-walker 

"Note that this display is part of ACES 2 and will be in the OCIO configs for ACES 2."

Hi Doug
In the [PR config](https://github.com/AcademySoftwareFoundation/OpenColorIO-Config-ACES/actions/runs/10648206791) I do not see **Display Gamma 2.2** in the display transforms. Will this change? I realize that the configs are a work in progress.

 I currently only see these displays 

  ST2084-P3-D65 - Display:
  Rec.2100-PQ - Display:
  P3-D65 - Display:
  Display P3 - Display:
  sRGB - Display:
  Rec.1886 Rec.709 - Display:
  Rec.2100-HLG - Display:

**Comment by doug-walker** [comment]
Hi Derek, yes it's not in the current draft but it should be in the next one. Thank you for your patience.  :)

**Comment by DiegoAUrso** [comment]
@doug-walker 
Has the Gamma 2.2 been officially added to the Aces 2 OCIO config?

Thanks for the help!

**Comment by doug-walker** [comment]
@DiegoAUrso , it is in the ACES 2 reference config, though that is not the one people actually use. We have been having discussions about adding it to the Studio config and that is planned to be added this summer. Sorry for the delay on this.
