### ISSUE TITLE
Should Linear sRGB and Linear Rec.709 exist as separate color spaces?

### ISSUE THREAD

**Issue by doug-walker** [AcademySoftwareFoundation/OpenColorIO-Config-ACES#74]
As we know, the primaries for sRGB were chosen to match those of Rec.709, and so it is common for these two terms to be used somewhat interchangeably in certain situations.  This may be confusing for people that are color management novices and so some thought should be given to how to use the terms in color space names.

The ACES 1.2 config has duplicate color spaces to handle this: `Utility - Linear - sRGB` and `Utility - Linear - Rec.709` are separate spaces that have the same definition under the hood.  Should we do something similar in the new configs?

This issue is to collect feedback about which approach should be used.

For novices, who don't understand that these two spaces are actually the same, having two separate menu options could lead to confusion.  For example, they may be vaguely familiar that these are the same but worry that the config may be implementing them slightly differently (otherwise, they might think, why have two separate options?).

One minor issue with the ACES 1.2 config is that these spaces are in different equality groups and thus are declared as being separate color spaces and thus do not automatically short circuit.  That said, the optimizer would optimize out the matrices, so a Processor from `Utility - Linear - sRGB` to `Utility - Linear - Rec.709` should still become a no-op (even if a bit farther down in the library).  

The bigger issue is for situations where color spaces are manipulated in a way that does not involve calling OCIO to get a Processor.  For example, in situations where color space names are used by external libraries (MaterialX, USD, etc.) and applications, having two names for the same space may occasionally cause unintended behavior since they may do optimizations outside of OCIO and not realize a pair of different color space names are actually the same.

One last point concerns the list of spaces that are intended to be shown for rendering space options (spaces that have encoding=scene-linear and category=working-space).  It seems especially redundant to have two separate, duplicate, spaces show up in this list.

One alternative that has been used elsewhere is to avoid duplicating the color spaces and simply combine the terms into a single name, for example: `Utility - Linear - sRGB / Rec.709`.  

**Advantages of having separate names**  `Utility - Linear - sRGB` and `Utility - Linear - Rec.709`
- Consistency with what was done in the ACES 1.2 config
- Avoid any confusion caused by combining them into one name

**Advantages of unifying the names**  `Utility - Linear - sRGB / Rec.709`
- Educate novices that these are actually the same space
- Avoid confusion over which menu item to pick
- Avoid making menus longer than they need to be
- Avoid issues with tools unable to optimize out an unnecessary conversion

p.s.
Some may observe that the ACES 1.2 config sometimes only uses Rec.709 and does not have an sRGB duplicate.  For example, `Utility - Gamma 2.2 - Rec.709 - Texture` has no equivalent `Utility - Gamma 2.2 - sRGB - Texture`.  I think this was a good design decision and consider it inappropriate to use "sRGB" with any gamma designation other than the piecewise curve since it would add to an already confusing situation.  The intent here is to explicitly exclude that topic from conversation in this issue.

**Comment by flord** [comment]
I believe a single color space is better. The fact that it educates novices is a compelling argument.

**Comment by chetannanda** [comment]
Yes, we should have single color space.

Adding ‘/‘ in the name may cause issues with the application that tokenise names on family separator to build menu.

**Comment by chriscolour** [comment]
As a supervisor for a color and vfx departement I would greatly appreciate having one option. Its maybe confusing in the start for some but in the long run we really want to educate all in understanding the separation of transfer curve and gamut, and that rec709 and sRGB have the same primaries

**Comment by frenchie1980** [comment]
I would also agree with having one version and like @chetannanda wonder whether the `/` could confuse some things.

On a related "separators" topic, was this amendment ever made to allow studios to choose their preferred separator for aliases:
https://lists.aswf.io/g/ocio-user/message/565

Currently the config is full of aliases using `_` as the word separator which makes them much harder to use predictably in filenames

**Comment by aarondemolder** [comment]
I am a supporter of a single option. But given the constant confusion between the transfer function and the colour space of sRGB, I would even suggest considering only having Rec.709. If we agree that we would like to educate novices, then not naming sRGB is probably how to do that, otherwise people may just choose it because it says sRGB.

Given that sRGB's primaries are _from_ ITU-R BT.709, I don't think this would be an incorrect approach. Though maybe a bit annoying for those starting out - it would mean they learn it sooner! A comment in docs could be a good way to give an overview of this?

**Comment by sharktacos** [comment]
> I would also agree with having one version and like @chetannanda wonder whether the `/` could confuse some things.

Yes, IIRC a slash in the name in Nuke creates a sub-menu.

**Comment by doug-walker** [comment]
Thank you for the feedback everyone!  We had a lot of discussion among the working group members and decided to go with a singl space named "Linear Rec.709 (sRGB)".  You will see this in the upcoming RC2 release.  It will have the following aliases:
[lin_rec709_srgb, Utility - Linear - Rec.709, lin_rec709, lin_srgb, Utility - Linear - sRGB].

@aarondemolder , I think you raise a good point about dropping "sRGB" from that name entirely.  However, there has been significant feedback from people who are confused on the topic and the group felt removing it would be going too far, given the audience for these configs.

Regarding the "separators" topic, we have removed the slashes from all other names to avoid the sub-menu problem in some applications that are not using the OCIO app-helpers to generate hierarchical menus.

**Comment by doug-walker** [comment]
Closing this issue as it has been implemented. They have been implemented as a single color space.
