### ISSUE TITLE
file_rules: defines a default rule using color-space 'ACES2065-1' that does not match the default role 'sRGB - Texture'

### ISSUE THREAD

**Issue by ggarra13** [AcademySoftwareFoundation/OpenColorIO-Config-ACES#79]
When loading the new studio-config-v1.0.0-rc1_aces-v1.3_ocio-v2.1.ocio, I get the following warning:

[OpenColorIO Warning]: file_rules: defines a default rule using color-space 'ACES2065-1' that does not match the default role 'sRGB - Texture'.

**Comment by KelSolaar** [comment]
Thank you @ggarra13, this should have been addressed!
